use_frameworks!

platform :ios, '8.0'

target 'FMCollectionLayout_Example' do
  pod 'FMCollectionLayout', :path => '../'
  pod 'Masonry'
  target 'FMCollectionLayout_Tests' do
    inherit! :search_paths
    
    
  end
end
