use_frameworks!

platform :ios, '8.0'

target 'FMLayoutKit_Example' do
  pod 'FMLayoutKit', :path => '../'
  pod 'Masonry'
#  pod 'MJRefresh'
  target 'FMLayoutKit_Tests' do
    inherit! :search_paths

    
  end
end
